[package]
name = "pollution_level"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
path = "src/main.rs"
name = "pollution_level"

[dependencies]
marine-rs-sdk ={ version = "0.6.13", features = ["logger"] }
log = "0.4.8"
